SELECT
	A.ACTION_DATE,
	P.PRODUCT,
	S.SUPPLIER,
	A.QTY,
	A.PRICE
FROM
	ACTIONS A
	JOIN PRODUCTS P ON A.PRODUCT_ID = P.ID
	JOIN SUPPLIERS S ON A.SUPPLIER_ID = S.ID
WHERE
	A.ACTION_DATE >= DATE '2016-01-01'
	AND A.ACTION_DATE <= DATE '2016-02-01'
ORDER BY A.ACTION_DATE DESC