SELECT
	COALESCE(B.BRAND, 'Без бренда') AS BRAND,
	SUM(A.QTY * A.PRICE) AS TOTAL_PRICE
FROM
	ACTIONS AS A
	JOIN PRODUCTS AS P ON A.PRODUCT_ID = P.ID
	LEFT JOIN BRANDS AS B ON P.BRAND_ID = B.ID
	GROUP BY BRAND
	ORDER BY TOTAL_PRICE DESC