SELECT
	A.SUPPLIER_ID,
	S.SUPPLIER,
	C.CATEGORY,
	COUNT(A.QTY * A.PRICE) AS TOT
FROM
	ACTIONS A
	JOIN PRODUCTS AS P ON A.PRODUCT_ID = P.ID
	JOIN CATEGORIES AS C ON P.CATEGORY_ID = C.ID
	INNER JOIN SUPPLIERS AS S ON A.SUPPLIER_ID = S.ID
	WHERE EXTRACT(YEAR FROM A.ACTION_DATE) = 2016
GROUP BY
	SUPPLIER_ID,
	SUPPLIER,
	C.CATEGORY