SELECT
	EXTRACT(
		YEAR
		FROM
			A.ACTION_DATE
	) AS YEAR,
	C.CATEGORY,
	ROUND(SUM(A.QTY * A.PRICE) / SUM(A.QTY), 2) AS AVG_PRICE,
	MAX(A.PRICE),
	MIN(A.PRICE)
FROM
	ACTIONS A
	JOIN PRODUCTS P ON A.PRODUCT_ID = P.ID
	JOIN CATEGORIES C ON P.CATEGORY_ID = C.ID
GROUP BY
	C.CATEGORY,
	EXTRACT(
		YEAR
		FROM
			A.ACTION_DATE
	)
ORDER BY
	C.CATEGORY,
	YEAR DESC