import type { Metadata } from "next";
import "./globals.css";
import { Gabarito } from 'next/font/google'

const gabarito = Gabarito({subsets:['latin']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode
}

const RootLayout = ({children}:Props) => {
  return (
    <html lang="en">
      <body className={`${gabarito.className} bg-black text-white`}>
        {children}
      </body>
    </html>
  );
}

export default RootLayout